# Generated by Django 5.2.1 on 2025-06-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["date", "performance_time_start"],
                "permissions": [("can_manage_event_engineer", "can_assign_engineers")],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="event_notes",
            field=models.TextField(blank=True, null=True, verbose_name="Event notes"),
        ),
    ]
